import type { KnowledgeBase } from "./types"
import { applyAuthoredPythonBasicTeachingEvidence } from "./python-basic-teaching-evidence"

export const PYTHON_BASIC_KNOWLEDGE_BASE: KnowledgeBase = applyAuthoredPythonBasicTeachingEvidence({
  module: "Python基础",
  version: "0.2.0",
  updatedAt: "2026-07-31",
  sources: ["Python 官方文档", "KnowBalance 自编教学切片"],
  items: [
    {
      sourceId: "K001",
      title: "Python 是什么",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K001_intro.md",
      snippet: "Python 是一种通用编程语言。",
      prerequisites: [],
      keywords: ["Python", "编程", "解释器", "脚本"],
      facts: [{"sourceId": "K001", "factId": "F001", "content": "Python 是一种通用编程语言。", "source_id": "K001", "fact_id": "F001"}, {"sourceId": "K001", "factId": "F002", "content": "Python 程序通常由解释器执行。", "source_id": "K001", "fact_id": "F002"}, {"sourceId": "K001", "factId": "F003", "content": "Python 适合编写脚本、数据处理和教学示例。", "source_id": "K001", "fact_id": "F003"}, {"sourceId": "K001", "factId": "F004", "content": "Python 语法简洁，用缩进表示代码块，强调代码可读性。", "source_id": "K001", "fact_id": "F004"}, {"sourceId": "K001", "factId": "F005", "content": "Python 是动态类型语言，变量无需声明类型即可直接赋值使用。", "source_id": "K001", "fact_id": "F005"}, {"sourceId": "K001", "factId": "F006", "content": "Python 自带丰富标准库，覆盖文件、网络、数学等常用功能。", "source_id": "K001", "fact_id": "F006"}, {"sourceId": "K001", "factId": "F007", "content": "Python 支持面向对象、函数式等多种编程范式。", "source_id": "K001", "fact_id": "F007"}, {"sourceId": "K001", "factId": "F008", "content": "Python 是解释型语言，源代码逐行翻译执行，无需提前编译。", "source_id": "K001", "fact_id": "F008"}, {"sourceId": "K001", "factId": "F009", "content": "目前官方只维护 Python 3 系列，Python 2 已停止支持。", "source_id": "K001", "fact_id": "F009"}, {"sourceId": "K001", "factId": "F010", "content": "Python 代码文件通常以 .py 为扩展名。", "source_id": "K001", "fact_id": "F010"}, {"sourceId": "K001", "factId": "F011", "content": "交互式环境（REPL）可逐行执行代码，适合快速试验。", "source_id": "K001", "fact_id": "F011"}, {"sourceId": "K001", "factId": "F012", "content": "Python 常应用于 Web 开发、数据分析、人工智能等领域。", "source_id": "K001", "fact_id": "F012"}],
      examples: [{"title": "Python 是什么 基础示例", "code": "print(\"Python 是什么\")\nprint(\"source: K001\")", "explanation": "该示例用于帮助学习者识别“Python 是什么”的基本用途。"}, {"title": "输出多行自我介绍", "code": "print(\"我是 Python 初学者\")\nprint(\"正在学习编程基础\")\nprint(\"Python 很容易上手\")", "explanation": "多个 print 逐行输出文本，演示 Python 程序的基本执行方式。"}],
      practiceTasks: ["解释 Python 的用途", "运行第一个 Python 程序", "在交互式环境中输入 print(\"Hello, Python\") 并观察输出"],
      quizItems: [{"level": 1, "type": "short", "question": "请说明“Python 是什么”的核心作用。", "answer": "参考该知识点的 F001 事实。", "sourceId": "K001", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“Python 是什么”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K001", "factId": "F002"}, {"level": 2, "type": "choice", "question": "Python 中表示代码块的方式是什么？", "answer": "缩进", "sourceId": "K001", "factId": "F004", "options": ["花括号 {}", "缩进", "begin/end", "分号"]}],
    },
    {
      sourceId: "K002",
      title: "变量与赋值",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K002_variables.md",
      snippet: "Python 使用 = 进行变量赋值。",
      prerequisites: ["K001"],
      keywords: ["变量", "赋值", "variable", "assignment", "保存数据"],
      facts: [{"sourceId": "K002", "factId": "F001", "content": "Python 使用 = 进行变量赋值。", "source_id": "K002", "fact_id": "F001"}, {"sourceId": "K002", "factId": "F002", "content": "变量名用于引用程序中的数据。", "source_id": "K002", "fact_id": "F002"}, {"sourceId": "K002", "factId": "F003", "content": "变量可以被重新赋值，新值会覆盖旧绑定。", "source_id": "K002", "fact_id": "F003"}, {"sourceId": "K002", "factId": "F004", "content": "变量名必须以字母或下划线开头，不能以数字开头。", "source_id": "K002", "fact_id": "F004"}, {"sourceId": "K002", "factId": "F005", "content": "变量名区分大小写，name 与 Name 是两个不同的变量。", "source_id": "K002", "fact_id": "F005"}, {"sourceId": "K002", "factId": "F006", "content": "关键字如 if、for、def 不能用作变量名。", "source_id": "K002", "fact_id": "F006"}, {"sourceId": "K002", "factId": "F007", "content": "变量实际上引用内存中的对象，赋值本质是建立绑定关系。", "source_id": "K002", "fact_id": "F007"}, {"sourceId": "K002", "factId": "F008", "content": "使用未赋值的变量会引发 NameError 错误。", "source_id": "K002", "fact_id": "F008"}, {"sourceId": "K002", "factId": "F009", "content": "变量可被赋值为不同类型，因为 Python 是动态类型语言。", "source_id": "K002", "fact_id": "F009"}, {"sourceId": "K002", "factId": "F010", "content": "多个变量可同时赋值，如 a, b = 1, 2。", "source_id": "K002", "fact_id": "F010"}, {"sourceId": "K002", "factId": "F011", "content": "链式赋值 a = b = 0 让多个变量引用同一个值。", "source_id": "K002", "fact_id": "F011"}, {"sourceId": "K002", "factId": "F012", "content": "约定用全大写命名表示常量，但 Python 不强制禁止修改。", "source_id": "K002", "fact_id": "F012"}, {"sourceId": "K002", "factId": "F013", "content": "在不含分支、循环或跳转的顺序结构中，Python 语句按书写顺序依次执行。", "source_id": "K002", "fact_id": "F013"}],
      examples: [{"title": "更新变量值", "code": "age = 18\nage = age + 1\nprint(age)", "explanation": "变量可以先保存旧值，再通过赋值语句更新为新值。"}, {"title": "同时赋值多个变量", "code": "name, age = \"小明\", 18\nprint(name, age)\na = b = 0\nprint(a, b)", "explanation": "元组解包与链式赋值可一次为多个变量赋值。"}],
      practiceTasks: ["定义 name、age 两个变量并输出", "判断 x = x + 1 的执行结果", "练习 a, b = b, a 交换两个变量的值"],
      quizItems: [{"level": 1, "type": "choice", "question": "变量赋值在 Python 中使用哪个符号？", "answer": "=", "sourceId": "K002", "factId": "F001", "options": ["=", "==", ":=", "=>"]}, {"level": 2, "type": "practice", "question": "请完成一个与“变量与赋值”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K002", "factId": "F002"}, {"level": 1, "type": "choice", "question": "以下哪个变量名是合法的？", "answer": "_count", "sourceId": "K002", "factId": "F004", "options": ["2count", "_count", "my-name", "if"]}],
    },
    {
      sourceId: "K003",
      title: "基本数据类型",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K003_data_types.md",
      snippet: "int 表示整数，float 表示小数。",
      prerequisites: ["K002"],
      keywords: ["数据类型", "int", "float", "str", "bool", "数字", "字符串"],
      facts: [{"sourceId":"K003","factId":"F001","content":"int 表示整数，float 表示小数。","source_id":"K003","fact_id":"F001"},{"sourceId":"K003","factId":"F002","content":"str 表示字符串文本。","source_id":"K003","fact_id":"F002"},{"sourceId":"K003","factId":"F003","content":"bool 表示 True 或 False 两种逻辑值。","source_id":"K003","fact_id":"F003"},{"sourceId":"K003","factId":"F004","content":"type(x) 返回 x 的类型对象，例如 print(type(3)) 显示 <class 'int'>。","source_id":"K003","fact_id":"F004"},{"sourceId":"K003","factId":"F005","content":"int(\"3\") 返回整数 3，float(\"3.5\") 返回小数 3.5，str(3) 返回字符串 \"3\"。","source_id":"K003","fact_id":"F005"},{"sourceId":"K003","factId":"F006","content":"None 表示“无值”，属于 NoneType 类型。","source_id":"K003","fact_id":"F006"},{"sourceId":"K003","factId":"F007","content":"除法运算结果总是 float 类型，即使能整除。","source_id":"K003","fact_id":"F007"},{"sourceId":"K003","factId":"F008","content":"float 是双精度浮点数，部分小数（如 0.1）无法精确表示。","source_id":"K003","fact_id":"F008"},{"sourceId":"K003","factId":"F009","content":"bool 是 int 的子类，True 等价于 1，False 等价于 0。","source_id":"K003","fact_id":"F009"},{"sourceId":"K003","factId":"F010","content":"字符串可用单引号或双引号括起，两种写法等价。","source_id":"K003","fact_id":"F010"},{"sourceId":"K003","factId":"F011","content":"complex 类型表示复数，如 3+4j。","source_id":"K003","fact_id":"F011"},{"sourceId":"K003","factId":"F012","content":"isinstance(x, T) 判断 x 是否属于类型 T，例如 isinstance(3, int) 返回 True。","source_id":"K003","fact_id":"F012"},{"sourceId":"K003","factId":"F013","source_id":"K003","fact_id":"F013","content":"int(\"3.5\") 不能把小数字符串转换为整数，会引发 ValueError；若输入允许小数，应先使用 float 解析，并按任务要求决定是否再转换为整数。","capabilities":["rule","boundary","contrast","example"]}],
      examples: [{"title": "识别基础类型", "code": "score = 95\nname = \"Li Hua\"\npassed = True\nprint(type(score), type(name), type(passed))", "explanation": "int、str、bool 表示不同类型的数据，后续运算前应先确认类型。"}, {"title": "字符串与数值的类型转换", "code": "num_str = \"95\"\nnum = int(num_str)\nprint(num + 5)\npi = float(\"3.14\")\nprint(type(pi))", "explanation": "int() 与 float() 把字符串转换为数值后才能参与算术运算。"}],
      practiceTasks: ["区分 3 与 \"3\" 的类型", "写出四种基础类型示例", "用 type() 检查 3、3.0、\"3\"、True 四种数据的类型"],
      quizItems: [{"level": 1, "type": "choice", "question": "\"95\" 在 Python 中通常属于哪种类型？", "answer": "str", "sourceId": "K003", "factId": "F001", "options": ["int", "float", "str", "bool"]}, {"level": 2, "type": "practice", "question": "请完成一个与“基本数据类型”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K003", "factId": "F002"}, {"level": 1, "type": "choice", "question": "type(True) 的结果是什么？", "answer": "<class 'bool'>", "sourceId": "K003", "factId": "F009", "options": ["<class 'int'>", "<class 'str'>", "<class 'bool'>", "<class 'float'>"]}],
    },
    {
      sourceId: "K004",
      title: "输入输出",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K004_input_output.md",
      snippet: "print 用于向屏幕输出内容。",
      prerequisites: ["K002", "K003"],
      keywords: ["input", "print", "输入", "输出", "交互"],
      facts: [{"sourceId":"K004","factId":"F001","content":"print 用于向屏幕输出内容。","source_id":"K004","fact_id":"F001"},{"sourceId":"K004","factId":"F002","content":"input 用于读取用户输入并返回字符串。","source_id":"K004","fact_id":"F002"},{"sourceId":"K004","factId":"F003","content":"需要数值计算时应把 input 结果转换为数字类型。","source_id":"K004","fact_id":"F003"},{"sourceId":"K004","factId":"F004","content":"print 默认以空格分隔多个参数，并以换行符结尾。","source_id":"K004","fact_id":"F004"},{"sourceId":"K004","factId":"F005","content":"print 的 sep 参数可自定义分隔符，end 参数可修改结尾字符。","source_id":"K004","fact_id":"F005"},{"sourceId":"K004","factId":"F006","content":"input 的字符串参数会作为提示文字显示。","source_id":"K004","fact_id":"F006"},{"sourceId":"K004","factId":"F007","content":"input 等待用户输入并按回车键结束读取。","source_id":"K004","fact_id":"F007"},{"sourceId":"K004","factId":"F008","content":"f-string 可在字符串中直接嵌入变量，如 f\"你好，{name}\"。","source_id":"K004","fact_id":"F008"},{"sourceId":"K004","factId":"F009","content":"print 的 file 参数可把输出重定向到文件对象。","source_id":"K004","fact_id":"F009"},{"sourceId":"K004","factId":"F010","content":"字符串的 format() 方法支持位置与关键字格式化。","source_id":"K004","fact_id":"F010"},{"sourceId":"K004","factId":"F011","content":"输入输出是程序与用户交互的基本方式，也是调试的常用手段。","source_id":"K004","fact_id":"F011"},{"sourceId":"K004","factId":"F012","content":"多个 print 默认换行输出，可用 end=\"\" 让输出不换行。","source_id":"K004","fact_id":"F012"},{"sourceId":"K004","factId":"F013","source_id":"K004","fact_id":"F013","content":"input 返回的是字符串；两个数字字符串使用 + 会拼接文本而不是数值相加，例如 \"2\" + \"3\" 得到 \"23\"，而 int(\"2\") + int(\"3\") 得到 5。","capabilities":["rule","boundary","contrast","example"]}],
      examples: [{"title": "读取姓名并输出问候", "code": "name = input(\"请输入你的姓名：\")\nprint(\"你好，\" + name + \"！欢迎来到Python学习。\")", "explanation": "input 读取用户输入，print 把拼接后的问候语输出到屏幕。"}, {"title": "读取数字并计算和", "code": "a = input(\"请输入第一个数：\")\nb = input(\"请输入第二个数：\")\ntotal = int(a) + int(b)\nprint(\"两数之和为：\", total)", "explanation": "input 返回字符串，int() 转换后才能做算术运算。"}],
      practiceTasks: ["用 input 读取两个数字并计算它们的和", "编写程序：读取用户姓名和年龄，输出格式化的自我介绍", "用 input 读取一个数字，用 f-string 输出它的平方"],
      quizItems: [{"level": 1, "type": "choice", "question": "input 函数返回的数据类型是什么？", "answer": "str", "sourceId": "K004", "factId": "F001", "options": ["int", "float", "str", "bool"]}, {"level": 2, "type": "practice", "question": "写一段代码：读取用户输入的两个数字，输出它们的乘积。", "answer": "能正确使用 int() 转换并完成乘法运算。", "sourceId": "K004", "factId": "F003"}, {"level": 2, "type": "practice", "question": "用 f-string 输出：\"我叫小明，今年 18 岁\"。", "answer": "能使用 f\"{变量}\" 语法嵌入变量。", "sourceId": "K004", "factId": "F008"}],
    },
    {
      sourceId: "K005",
      title: "运算符",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K005_operators.md",
      snippet: "算术运算符可进行加减乘除等计算。",
      prerequisites: ["K003"],
      keywords: ["运算符", "加减乘除", "比较", "逻辑", "operator"],
      facts: [{"sourceId": "K005", "factId": "F001", "content": "算术运算符可进行加减乘除等计算。", "source_id": "K005", "fact_id": "F001"}, {"sourceId": "K005", "factId": "F002", "content": "比较运算符返回布尔值。", "source_id": "K005", "fact_id": "F002"}, {"sourceId": "K005", "factId": "F003", "content": "逻辑运算符 and、or、not 用于组合条件。", "source_id": "K005", "fact_id": "F003"}, {"sourceId": "K005", "factId": "F004", "content": "+ 与 * 也可用于字符串和列表，分别表示拼接与重复。", "source_id": "K005", "fact_id": "F004"}, {"sourceId": "K005", "factId": "F005", "content": "% 取模返回余数，// 整除向下取整，** 表示幂运算。", "source_id": "K005", "fact_id": "F005"}, {"sourceId": "K005", "factId": "F006", "content": "比较运算符包括 ==、!=、<、>、<=、>= 六种。", "source_id": "K005", "fact_id": "F006"}, {"sourceId": "K005", "factId": "F007", "content": "== 比较值是否相等，is 判断是否为同一个对象。", "source_id": "K005", "fact_id": "F007"}, {"sourceId": "K005", "factId": "F008", "content": "赋值 = 与比较 == 含义不同，是初学者常见易错点。", "source_id": "K005", "fact_id": "F008"}, {"sourceId": "K005", "factId": "F009", "content": "复合赋值 +=、-= 等可简化变量更新写法。", "source_id": "K005", "fact_id": "F009"}, {"sourceId": "K005", "factId": "F010", "content": "in 可判断元素是否存在于序列或容器中。", "source_id": "K005", "fact_id": "F010"}, {"sourceId": "K005", "factId": "F011", "content": "逻辑运算 and、or 采用短路求值，能提前确定结果就停止计算。", "source_id": "K005", "fact_id": "F011"}, {"sourceId": "K005", "factId": "F012", "content": "运算符有优先级：** 高于乘除，乘除高于加减，比较与逻辑优先级更低。", "source_id": "K005", "fact_id": "F012"}],
      examples: [{"title": "成绩平均分计算", "code": "score1 = 85\nscore2 = 92\nscore3 = 78\naverage = (score1 + score2 + score3) / 3\nprint(\"平均分：\", average)", "explanation": "算术运算符 + 和 / 用于计算多名学生成绩的平均分。"}, {"title": "判断是否及格", "code": "score = 73\npassed = score >= 60\nprint(\"是否及格：\", passed)\n\nif passed and score < 90:\n    print(\"已通过，可以继续提升。\")", "explanation": "比较运算符 >= 判断分数是否及格，逻辑运算符 and 组合多个条件。"}],
      practiceTasks: ["计算表达式 (85 + 92) / 3 的结果", "编写判断闰年的条件表达式", "写出 (2 + 3) * 4 ** 2 的运算结果并说明优先级"],
      quizItems: [{"level": 1, "type": "choice", "question": "Python 中 7 // 2 的结果是？", "answer": "3", "sourceId": "K005", "factId": "F001", "options": ["3.5", "3", "4", "报错"]}, {"level": 2, "type": "practice", "question": "写代码判断一个年份是否能被 4 整除且不能被 100 整除。", "answer": "能综合使用取模 % 和逻辑运算符 and。", "sourceId": "K005", "factId": "F003"}, {"level": 2, "type": "choice", "question": "Python 中 2 ** 3 ** 2 的结果是？", "answer": "512", "sourceId": "K005", "factId": "F012", "options": ["64", "512", "36", "报错"]}],
    },
    {
      sourceId: "K006",
      title: "条件判断",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K006_conditionals.md",
      snippet: "if 根据条件真假决定是否执行代码块。",
      prerequisites: ["K003", "K005"],
      keywords: ["if", "elif", "else", "条件", "判断", "分支"],
      facts: [{"sourceId": "K006", "factId": "F001", "content": "if 根据条件真假决定是否执行代码块。", "source_id": "K006", "fact_id": "F001"}, {"sourceId": "K006", "factId": "F002", "content": "elif 用于追加多个互斥条件分支。", "source_id": "K006", "fact_id": "F002"}, {"sourceId": "K006", "factId": "F003", "content": "else 处理前面条件都不满足的情况。", "source_id": "K006", "fact_id": "F003"}, {"sourceId": "K006", "factId": "F004", "content": "if 语句以冒号结尾，其代码块必须缩进。", "source_id": "K006", "fact_id": "F004"}, {"sourceId": "K006", "factId": "F005", "content": "非零数字、非空字符串与列表在条件中视为 True。", "source_id": "K006", "fact_id": "F005"}, {"sourceId": "K006", "factId": "F006", "content": "0、空字符串、空列表、None 在条件中视为 False。", "source_id": "K006", "fact_id": "F006"}, {"sourceId": "K006", "factId": "F007", "content": "if/elif/else 链按顺序判断，只会执行第一个为真的分支。", "source_id": "K006", "fact_id": "F007"}, {"sourceId": "K006", "factId": "F008", "content": "条件可嵌套，但嵌套过深会影响代码可读性。", "source_id": "K006", "fact_id": "F008"}, {"sourceId": "K006", "factId": "F009", "content": "三元表达式 x if 条件 else y 可在一行完成简单判断。", "source_id": "K006", "fact_id": "F009"}, {"sourceId": "K006", "factId": "F010", "content": "比较可链式书写，如 0 < x < 10 等价于两个比较的与运算。", "source_id": "K006", "fact_id": "F010"}, {"sourceId": "K006", "factId": "F011", "content": "条件表达式与赋值结合时注意优先级，建议加括号明确。", "source_id": "K006", "fact_id": "F011"}, {"sourceId": "K006", "factId": "F012", "content": "条件判断结果可直接赋值给变量，如 flag = score >= 60。", "source_id": "K006", "fact_id": "F012"}],
      examples: [{"title": "成绩等级判断", "code": "score = 82\nif score >= 60:\n    print(\"pass\")\nelse:\n    print(\"retry\")", "explanation": "if/else 根据条件真假选择不同分支。"}, {"title": "多分支成绩等级", "code": "score = 85\nif score >= 90:\n    print(\"优秀\")\nelif score >= 60:\n    print(\"及格\")\nelse:\n    print(\"不及格\")", "explanation": "if/elif/else 按顺序匹配，只会执行第一个满足条件的分支。"}],
      practiceTasks: ["根据分数输出及格或不及格", "写出多分支等级判断", "用 if/elif/else 根据成绩输出 优秀/及格/不及格"],
      quizItems: [{"level": 1, "type": "choice", "question": "当 if 条件不满足且存在 else 时，程序会执行什么？", "answer": "else 分支", "sourceId": "K006", "factId": "F001", "options": ["if 分支", "else 分支", "两个分支都执行", "程序停止"]}, {"level": 2, "type": "practice", "question": "请完成一个与“条件判断”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K006", "factId": "F002"}, {"level": 2, "type": "practice", "question": "用三元表达式实现：score >= 60 时输出\"及格\"，否则输出\"不及格\"。", "answer": "能使用 x if 条件 else y 的写法。", "sourceId": "K006", "factId": "F009"}],
    },
    {
      sourceId: "K007",
      title: "for 循环",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K007_for_loop.md",
      snippet: "for 循环常用于遍历序列中的元素。",
      prerequisites: ["K002", "K003"],
      keywords: ["for", "循环", "遍历", "重复执行", "序列"],
      facts: [{"sourceId":"K007","factId":"F001","content":"for 循环常用于遍历序列中的元素。","source_id":"K007","fact_id":"F001"},{"sourceId":"K007","factId":"F002","content":"for 循环适合对列表、字符串等对象逐个处理。","source_id":"K007","fact_id":"F002"},{"sourceId":"K007","factId":"F003","content":"range 可生成整数序列配合 for 重复执行固定次数。","source_id":"K007","fact_id":"F003"},{"sourceId":"K007","factId":"F004","content":"range(start, stop, step) 可指定起始、结束与步长。","source_id":"K007","fact_id":"F004"},{"sourceId":"K007","factId":"F005","content":"range 不包含结束值，range(3) 生成 0、1、2。","source_id":"K007","fact_id":"F005"},{"sourceId":"K007","factId":"F006","content":"break 可立即终止整个循环。","source_id":"K007","fact_id":"F006"},{"sourceId":"K007","factId":"F007","content":"continue 跳过本次循环剩余语句，进入下一次迭代。","source_id":"K007","fact_id":"F007"},{"sourceId":"K007","factId":"F008","content":"for 循环可搭配 else，循环未被 break 中断时执行 else。","source_id":"K007","fact_id":"F008"},{"sourceId":"K007","factId":"F009","content":"enumerate() 可同时获取元素及其索引。","source_id":"K007","fact_id":"F009"},{"sourceId":"K007","factId":"F010","content":"for 可遍历字典的键、值或 items() 键值对。","source_id":"K007","fact_id":"F010"},{"sourceId":"K007","factId":"F011","content":"循环变量只是对元素的引用，直接赋值不会修改原序列。","source_id":"K007","fact_id":"F011"},{"sourceId":"K007","factId":"F012","content":"需要按索引修改列表时，可结合 range 与 len 遍历。","source_id":"K007","fact_id":"F012"},{"sourceId":"K007","factId":"F013","source_id":"K007","fact_id":"F013","content":"range 的 stop 不包含在结果中，例如 list(range(1, 4)) 为 [1, 2, 3]；需要遍历整数 1 到 4 时应使用 range(1, 5)，否则会遗漏端点。","capabilities":["rule","boundary","contrast","example"]}],
      examples: [{"title": "遍历成绩列表", "code": "scores = [80, 90, 75]\nfor score in scores:\n    print(score)", "explanation": "for 循环会依次取出列表中的每个成绩，适合重复处理。"}, {"title": "计算 1 到 100 的和", "code": "total = 0\nfor i in range(1, 101):\n    total += i\nprint(\"1 到 100 的和：\", total)", "explanation": "range(1, 101) 生成 1 到 100 的整数序列，循环内累加求和。"}],
      practiceTasks: ["遍历列表并打印每个元素", "用 for 计算 1 到 10 的和", "用 for 循环遍历字符串并统计其中字母 e 的个数"],
      quizItems: [{"level": 1, "type": "choice", "question": "for 循环最适合用于什么场景？", "answer": "遍历序列", "sourceId": "K007", "factId": "F001", "options": ["遍历序列", "定义变量", "捕获异常", "导入模块"]}, {"level": 2, "type": "practice", "question": "请完成一个与“for 循环”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K007", "factId": "F002"}, {"level": 2, "type": "practice", "question": "用 range 输出 1 到 10 中所有偶数。", "answer": "能用 range 步长或取模判断实现。", "sourceId": "K007", "factId": "F004"}],
    },
    {
      sourceId: "K008",
      title: "while 循环",
      module: "Python基础",
      difficulty: "beginner",
      file: "knowledge_base/python_basic/K008_while_loop.md",
      snippet: "while 会在条件为 True 时重复执行代码块。",
      prerequisites: ["K006"],
      keywords: ["while", "循环", "条件循环", "重复执行"],
      facts: [{"sourceId": "K008", "factId": "F001", "content": "while 会在条件为 True 时重复执行代码块。", "source_id": "K008", "fact_id": "F001"}, {"sourceId": "K008", "factId": "F002", "content": "对需要结束的 while 循环，应保证存在退出路径以避免意外的无限循环：可以更新影响条件的状态使条件变为 False，也可以用 break 退出。", "source_id": "K008", "fact_id": "F002"}, {"sourceId": "K008", "factId": "F003", "content": "while 适合重复次数不确定但停止条件明确的任务。", "source_id": "K008", "fact_id": "F003"}, {"sourceId": "K008", "factId": "F004", "content": "while 每次迭代前先判断条件，条件为 False 时退出循环。", "source_id": "K008", "fact_id": "F004"}, {"sourceId": "K008", "factId": "F005", "content": "break 可立即终止整个循环。", "source_id": "K008", "fact_id": "F005"}, {"sourceId": "K008", "factId": "F006", "content": "continue 跳过本次迭代，直接回到条件判断。", "source_id": "K008", "fact_id": "F006"}, {"sourceId": "K008", "factId": "F007", "content": "while 可搭配 else，条件变 False 正常结束时执行 else。", "source_id": "K008", "fact_id": "F007"}, {"sourceId": "K008", "factId": "F008", "content": "while True 配合 break 可实现先执行后判断的循环结构。", "source_id": "K008", "fact_id": "F008"}, {"sourceId": "K008", "factId": "F009", "content": "死循环会持续占用 CPU，导致程序卡死或无响应。", "source_id": "K008", "fact_id": "F009"}, {"sourceId": "K008", "factId": "F010", "content": "循环变量应在循环外初始化，在循环内更新。", "source_id": "K008", "fact_id": "F010"}, {"sourceId": "K008", "factId": "F011", "content": "while 适合轮询状态或等待满足条件再退出的场景。", "source_id": "K008", "fact_id": "F011"}, {"sourceId": "K008", "factId": "F012", "content": "循环体内至少要有一条语句，暂无逻辑时用 pass 占位。", "source_id": "K008", "fact_id": "F012"}],
      examples: [{"title": "从 1 数到 5", "code": "count = 1\nwhile count <= 5:\n    print(\"第\", count, \"次\")\n    count = count + 1", "explanation": "每次循环把 count 加 1，直到 count > 5 时条件为 False 退出。"}, {"title": "直到输入正确密码", "code": "password = \"\"\nwhile password != \"abc123\":\n    password = input(\"请输入密码：\")\nprint(\"登录成功！\")", "explanation": "循环持续要求输入，直到用户输入正确密码，属于重复次数不确定但终止条件明确的典型场景。"}],
      practiceTasks: ["用 while 实现 1 到 100 累加求和", "写一个猜数字游戏：程序想一个 1-100 的数，用户猜直到猜对", "用 while 实现：不断输入数字并累加，输入 0 时结束并输出总和"],
      quizItems: [{"level": 1, "type": "choice", "question": "以下哪段代码会导致死循环？", "answer": "x=5; while x>0: print(x)", "sourceId": "K008", "factId": "F002", "options": ["while False: print(1)", "while True: break", "x=0; while x<5: x+=1", "x=5; while x>0: print(x)"]}, {"level": 2, "type": "practice", "question": "用 while 循环计算 1 到 100 的和。", "answer": "能正确使用累计变量并在循环内更新条件变量。", "sourceId": "K008", "factId": "F001"}, {"level": 1, "type": "choice", "question": "while True 循环中，用什么语句可以立即退出循环？", "answer": "break", "sourceId": "K008", "factId": "F005", "options": ["continue", "break", "pass", "exit"]}],
    },
    {
      sourceId: "K009",
      title: "列表",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K009_list.md",
      snippet: "列表可用于保存多个有序元素。",
      prerequisites: ["K002", "K003"],
      keywords: ["列表", "list", "数组", "成绩", "一组数据", "保存多个"],
      facts: [{"sourceId":"K009","factId":"F001","content":"列表可用于保存多个有序元素。","source_id":"K009","fact_id":"F001"},{"sourceId":"K009","factId":"F002","content":"列表元素可以通过索引访问。","source_id":"K009","fact_id":"F002"},{"sourceId":"K009","factId":"F003","content":"append 可向列表末尾添加元素。","source_id":"K009","fact_id":"F003"},{"sourceId":"K009","factId":"F004","content":"列表用方括号 [] 创建，元素之间用逗号分隔。","source_id":"K009","fact_id":"F004"},{"sourceId":"K009","factId":"F005","content":"索引从 0 开始，list[0] 是第一个元素。","source_id":"K009","fact_id":"F005"},{"sourceId":"K009","factId":"F006","content":"负索引从末尾计数，list[-1] 是最后一个元素。","source_id":"K009","fact_id":"F006"},{"sourceId":"K009","factId":"F007","content":"切片 list[start:end] 截取子列表，结束索引不包含在内。","source_id":"K009","fact_id":"F007"},{"sourceId":"K009","factId":"F008","content":"len() 返回列表元素个数。","source_id":"K009","fact_id":"F008"},{"sourceId":"K009","factId":"F009","content":"insert 按索引插入元素，remove 按值删除第一个匹配项。","source_id":"K009","fact_id":"F009"},{"sourceId":"K009","factId":"F010","content":"pop 删除并返回指定位置元素，默认删除末尾元素。","source_id":"K009","fact_id":"F010"},{"sourceId":"K009","factId":"F011","content":"列表是可变对象，元素可修改、增删。","source_id":"K009","fact_id":"F011"},{"sourceId":"K009","factId":"F012","content":"列表可保存不同类型元素，也可嵌套其他列表。","source_id":"K009","fact_id":"F012"},{"sourceId":"K009","factId":"F013","content":"列表推导式如 [x*2 for x in range(5)] 可简洁生成新列表。","source_id":"K009","fact_id":"F013"},{"sourceId":"K009","factId":"F014","content":"用 + 或 extend() 可合并两个列表。","source_id":"K009","fact_id":"F014"},{"sourceId":"K009","factId":"F015","source_id":"K009","fact_id":"F015","content":"访问列表中不存在的单个索引会引发 IndexError；长度为 n 的列表，其非负有效索引是 0 到 n-1，空列表没有可访问的元素。","capabilities":["rule","boundary","contrast","example"]}],
      examples: [{"title": "保存多名学生成绩", "code": "scores = [80, 90, 75]\nscores.append(88)\nprint(scores)", "explanation": "列表适合保存多个有序数据，append 可追加新元素。"}, {"title": "索引与切片", "code": "scores = [80, 90, 75, 88]\nprint(\"第一个：\", scores[0])\nprint(\"最后一个：\", scores[-1])\nprint(\"前两个：\", scores[:2])", "explanation": "正索引从 0 开始，负索引从末尾计数，切片截取子列表。"}],
      practiceTasks: ["创建成绩列表并计算长度", "向列表追加一个新成绩", "用切片取出列表的前三个元素并输出"],
      quizItems: [{"level": 1, "type": "choice", "question": "向列表末尾添加元素常用哪个方法？", "answer": "append", "sourceId": "K009", "factId": "F001", "options": ["append", "split", "return", "import"]}, {"level": 2, "type": "practice", "question": "请完成一个与“列表”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K009", "factId": "F002"}, {"level": 2, "type": "practice", "question": "给定 lst = [10, 20, 30]，用切片取出 [20, 30]。", "answer": "能写出 lst[1:] 并理解切片规则。", "sourceId": "K009", "factId": "F007"}],
    },
    {
      sourceId: "K010",
      title: "字典",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K010_dict.md",
      snippet: "字典使用键值对保存数据。",
      prerequisites: ["K002", "K003"],
      keywords: ["字典", "dict", "键值对", "姓名", "查成绩", "映射"],
      facts: [{"sourceId": "K010", "factId": "F001", "content": "字典使用键值对保存数据。", "source_id": "K010", "fact_id": "F001"}, {"sourceId": "K010", "factId": "F002", "content": "字典适合根据唯一键快速查找对应值。", "source_id": "K010", "fact_id": "F002"}, {"sourceId": "K010", "factId": "F003", "content": "可以用 dict[key] 访问指定键的值。", "source_id": "K010", "fact_id": "F003"}, {"sourceId": "K010", "factId": "F004", "content": "字典用花括号 {} 创建，键与值之间用冒号分隔。", "source_id": "K010", "fact_id": "F004"}, {"sourceId": "K010", "factId": "F005", "content": "字典的键必须唯一，值可以是任意类型。", "source_id": "K010", "fact_id": "F005"}, {"sourceId": "K010", "factId": "F006", "content": "键必须是不可变对象，如字符串、数字或元组。", "source_id": "K010", "fact_id": "F006"}, {"sourceId": "K010", "factId": "F007", "content": "dict[key] = value 可新增或修改键值对。", "source_id": "K010", "fact_id": "F007"}, {"sourceId": "K010", "factId": "F008", "content": ".get(key, 默认值) 在键不存在时返回默认值而不是报错。", "source_id": "K010", "fact_id": "F008"}, {"sourceId": "K010", "factId": "F009", "content": "访问不存在的键会抛出 KeyError。", "source_id": "K010", "fact_id": "F009"}, {"sourceId": "K010", "factId": "F010", "content": ".keys()、.values()、.items() 分别返回键、值、键值对的视图。", "source_id": "K010", "fact_id": "F010"}, {"sourceId": "K010", "factId": "F011", "content": "del dict[key] 删除键值对，in 判断键是否存在。", "source_id": "K010", "fact_id": "F011"}, {"sourceId": "K010", "factId": "F012", "content": "从 Python 3.7 起字典保持键的插入顺序。", "source_id": "K010", "fact_id": "F012"}],
      examples: [{"title": "建立学生成绩字典", "code": "scores = {\"小明\": 92, \"小红\": 85, \"小刚\": 78}\nprint(\"小红的成绩：\", scores[\"小红\"])\nscores[\"小刚\"] = 82\nscores[\"小丽\"] = 95\nprint(\"全部成绩：\", scores)", "explanation": "字典用姓名做键、成绩做值，通过键快速查找对应值。"}, {"title": "遍历字典", "code": "scores = {\"小明\": 92, \"小红\": 85, \"小刚\": 78}\ntotal = 0\nfor name, score in scores.items():\n    print(name, \":\", score)\n    total += score\nprint(\"平均分：\", total / len(scores))", "explanation": ".items() 同时取出键和值，适合批量处理字典内容。"}],
      practiceTasks: ["建立学生姓名到成绩的字典并遍历输出", "使用 .get() 方法安全访问字典，处理不存在的键", "用 .get() 安全读取字典中可能不存在的键"],
      quizItems: [{"level": 1, "type": "choice", "question": "访问字典中不存在的键会引发什么错误？", "answer": "KeyError", "sourceId": "K010", "factId": "F003", "options": ["ValueError", "TypeError", "KeyError", "IndexError"]}, {"level": 2, "type": "practice", "question": "给定 scores = {\"小明\": 92, \"小红\": 85}，写代码查找\"小刚\"的成绩，如果不存在输出\"未找到\"。", "answer": "能使用 .get() 或 in 关键字安全访问。", "sourceId": "K010", "factId": "F002"}, {"level": 1, "type": "choice", "question": "d = {\"a\": 1}，d.get(\"b\", 0) 的返回值是？", "answer": "0", "sourceId": "K010", "factId": "F008", "options": ["None", "0", "报错", "\"b\""]}],
    },
    {
      sourceId: "K011",
      title: "元组与集合",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K011_tuple_set.md",
      snippet: "元组是有序且通常不可变的数据容器。",
      prerequisites: ["K003", "K009"],
      keywords: ["元组", "tuple", "集合", "set", "去重"],
      facts: [{"sourceId": "K011", "factId": "F001", "content": "元组是有序且通常不可变的数据容器。", "source_id": "K011", "fact_id": "F001"}, {"sourceId": "K011", "factId": "F002", "content": "集合用于保存不重复元素。", "source_id": "K011", "fact_id": "F002"}, {"sourceId": "K011", "factId": "F003", "content": "集合适合做去重和成员判断。", "source_id": "K011", "fact_id": "F003"}, {"sourceId": "K011", "factId": "F004", "content": "元组用圆括号 () 创建，元素用逗号分隔。", "source_id": "K011", "fact_id": "F004"}, {"sourceId": "K011", "factId": "F005", "content": "元组创建后不能修改、添加或删除元素。", "source_id": "K011", "fact_id": "F005"}, {"sourceId": "K011", "factId": "F006", "content": "单元素元组必须写成 (1,)，否则只是普通括号表达式。", "source_id": "K011", "fact_id": "F006"}, {"sourceId": "K011", "factId": "F007", "content": "元组支持索引与切片，访问方式与列表一致。", "source_id": "K011", "fact_id": "F007"}, {"sourceId": "K011", "factId": "F008", "content": "元组可作字典的键，列表因可变不能作键。", "source_id": "K011", "fact_id": "F008"}, {"sourceId": "K011", "factId": "F009", "content": "空集合必须用 set() 创建，{} 表示空字典。", "source_id": "K011", "fact_id": "F009"}, {"sourceId": "K011", "factId": "F010", "content": "集合元素必须可哈希，列表和字典不能作为集合元素。", "source_id": "K011", "fact_id": "F010"}, {"sourceId": "K011", "factId": "F011", "content": "集合支持 | 并集、& 交集、- 差集等运算。", "source_id": "K011", "fact_id": "F011"}, {"sourceId": "K011", "factId": "F012", "content": "集合是无序容器，不能通过索引访问元素。", "source_id": "K011", "fact_id": "F012"}],
      examples: [{"title": "用元组表示固定坐标", "code": "point = (3, 5)\nx, y = point\nprint(\"坐标：\", x, y)\n# point[0] = 10  # TypeError", "explanation": "元组适合存储不应被修改的固定数据。"}, {"title": "用集合去重", "code": "scores = [85, 92, 85, 78, 92, 85]\nunique_scores = set(scores)\nprint(\"去重后的成绩：\", unique_scores)\n\nif 85 in unique_scores:\n    print(\"有 85 分这个成绩\")", "explanation": "集合自动去除重复元素，适合数据去重和快速成员检查。"}],
      practiceTasks: ["用集合去除姓名列表中的重复项", "说明元组和列表的核心差异（可变性）", "创建元组 (1, 2, 3) 与集合 {1, 2, 3}，比较它们能否修改"],
      quizItems: [{"level": 1, "type": "choice", "question": "以下哪个操作会报错？", "answer": "t=(1,2); t[0]=3", "sourceId": "K011", "factId": "F001", "options": ["t=(1,2); print(t[0])", "t=(1,2); t[0]=3", "s=set([1,2,2]); print(s)", "s={1,2,3}; print(1 in s)"]}, {"level": 2, "type": "practice", "question": "给定 names = [\"小明\",\"小红\",\"小明\",\"小刚\",\"小红\"]，用 set 去重后转为列表输出。", "answer": "能使用 set() 和 list() 完成去重转换。", "sourceId": "K011", "factId": "F002"}, {"level": 2, "type": "practice", "question": "用集合运算找出 {1, 2, 3} 与 {2, 3, 4} 的交集。", "answer": "能用 & 运算符求交集。", "sourceId": "K011", "factId": "F011"}],
    },
    {
      sourceId: "K012",
      title: "字符串常用操作",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K012_string.md",
      snippet: "字符串是字符序列。",
      prerequisites: ["K003"],
      keywords: ["字符串", "str", "切片", "split", "join", "文本"],
      facts: [{"sourceId": "K012", "factId": "F001", "content": "字符串是字符序列。", "source_id": "K012", "fact_id": "F001"}, {"sourceId": "K012", "factId": "F002", "content": "s.split(sep) 按分隔符 sep 拆分字符串 s，并返回由各段组成的列表。", "source_id": "K012", "fact_id": "F002"}, {"sourceId": "K012", "factId": "F003", "content": "sep.join(parts) 用分隔符 sep 连接字符串序列 parts，并返回连接后的新字符串。", "source_id": "K012", "fact_id": "F003"}, {"sourceId": "K012", "factId": "F004", "content": "字符串不可原地修改字符；文本变换可以返回字符串，拆分和查询等操作的返回类型由具体方法决定。", "source_id": "K012", "fact_id": "F004"}, {"sourceId": "K012", "factId": "F005", "content": "字符串支持索引与切片，如 s[0]、s[1:3]。", "source_id": "K012", "fact_id": "F005"}, {"sourceId": "K012", "factId": "F006", "content": "len(s) 返回字符串 s 的字符数量，中文字符按一个字符计数。", "source_id": "K012", "fact_id": "F006"}, {"sourceId": "K012", "factId": "F007", "content": "f-string 在字符串前加 f，用 {} 嵌入变量或表达式。", "source_id": "K012", "fact_id": "F007"}, {"sourceId": "K012", "factId": "F008", "content": "s.strip() 返回去除首尾空白的新字符串，s.lower()/s.upper() 返回转换大小写后的新字符串。", "source_id": "K012", "fact_id": "F008"}, {"sourceId": "K012", "factId": "F009", "content": "s.replace(old, new) 返回替换子串后的新字符串，s.find(sub) 返回子串首次出现的位置。", "source_id": "K012", "fact_id": "F009"}, {"sourceId": "K012", "factId": "F010", "content": "s.startswith(prefix) 与 s.endswith(suffix) 分别返回字符串是否以指定内容开头或结尾的布尔值。", "source_id": "K012", "fact_id": "F010"}, {"sourceId": "K012", "factId": "F011", "content": "字符串比较按字符的 Unicode 码点逐字符进行。", "source_id": "K012", "fact_id": "F011"}, {"sourceId": "K012", "factId": "F012", "content": "三引号字符串可跨行书写，常用于多行文本与文档字符串。", "source_id": "K012", "fact_id": "F012"}],
      examples: [{"title": "拆分和处理成绩数据", "code": "data = \"小明:92,小红:85,小刚:78\"\npairs = data.split(\",\")\nfor pair in pairs:\n    name, score = pair.split(\":\")\n    print(name, \"的成绩是\", score)", "explanation": "split 把逗号分隔的字符串拆成列表，再逐个拆分出姓名和成绩。"}, {"title": "拼接报告", "code": "names = [\"小明\", \"小红\", \"小刚\"]\nscores = [92, 85, 78]\nlines = []\nfor i in range(len(names)):\n    lines.append(names[i] + \"：\" + str(scores[i]) + \"分\")\nreport = \"\\n\".join(lines)\nprint(report)", "explanation": "join 把每行报告用换行符连接成完整的段落文本。"}],
      practiceTasks: ["用 split 和 join 处理并重组 csv 格式数据", "编写程序：把成绩列表用逗号拼接为一行字符串", "用 replace 把句子中的逗号替换为空格"],
      quizItems: [{"level": 1, "type": "choice", "question": "\"a,b,c\".split(\",\") 的结果是？", "answer": "[\"a\",\"b\",\"c\"]", "sourceId": "K012", "factId": "F002", "options": ["\"abc\"", "[\"a\",\"b\",\"c\"]", "\"a b c\"", "[\"abc\"]"]}, {"level": 2, "type": "practice", "question": "给定 data = \"张三:88,李四:95,王五:72\"，用 split 解析后输出每个同学的姓名和成绩。", "answer": "能使用 split 分步解析字符串。", "sourceId": "K012", "factId": "F002"}, {"level": 1, "type": "choice", "question": "\"Hello\".lower() 的结果是？", "answer": "\"hello\"", "sourceId": "K012", "factId": "F008", "options": ["\"HELLO\"", "\"hello\"", "\"Hello\"", "报错"]}],
    },
    {
      sourceId: "K013",
      title: "函数定义与调用",
      module: "Python基础",
      difficulty: "basic",
      // 冻结可完整支撑“函数是什么—怎样定义—何时执行”的最小核心闭包。
      // F001/F003 分别被 F004/F006 更完整地涵盖；避免生成器为了正常讲清
      // 复用、定义行和调用时机而被迫使用核心证据之外的事实。
      coreFactIds: ["F002", "F004", "F006"],
      file: "knowledge_base/python_basic/K013_function.md",
      snippet: "def 用于定义函数。",
      prerequisites: ["K002", "K006", "K007"],
      keywords: ["函数", "def", "调用", "复用", "function"],
      facts: [{"sourceId": "K013", "factId": "F001", "content": "def 用于定义函数。", "source_id": "K013", "fact_id": "F001"}, {"sourceId": "K013", "factId": "F002", "content": "函数把可复用逻辑封装成命名代码块。", "source_id": "K013", "fact_id": "F002"}, {"sourceId": "K013", "factId": "F003", "content": "调用函数时会执行函数体中的代码。", "source_id": "K013", "fact_id": "F003"}, {"sourceId": "K013", "factId": "F004", "content": "函数定义以 def 开头，后跟函数名、圆括号与冒号；圆括号内可以列出参数，也可以为空。", "source_id": "K013", "fact_id": "F004"}, {"sourceId": "K013", "factId": "F005", "content": "函数体必须缩进，通常使用四个空格。", "source_id": "K013", "fact_id": "F005"}, {"sourceId": "K013", "factId": "F006", "content": "定义函数不会立即执行，只有调用时才运行函数体；同一个函数可以按需调用多次。", "source_id": "K013", "fact_id": "F006"}, {"sourceId": "K013", "factId": "F007", "content": "函数名必须以字母或下划线开头，后续可使用字母、数字或下划线，并且不能使用 Python 关键字。", "source_id": "K013", "fact_id": "F007"}, {"sourceId": "K013", "factId": "F008", "content": "函数可被多次调用，是代码复用的基本手段。", "source_id": "K013", "fact_id": "F008"}, {"sourceId": "K013", "factId": "F009", "content": "函数内定义的局部变量只在函数内部可见。", "source_id": "K013", "fact_id": "F009"}, {"sourceId": "K013", "factId": "F010", "content": "len、print、sum 等内置函数可直接调用。", "source_id": "K013", "fact_id": "F010"}, {"sourceId": "K013", "factId": "F011", "content": "函数可以调用其他函数，组合完成复杂任务。", "source_id": "K013", "fact_id": "F011"}, {"sourceId": "K013", "factId": "F012", "content": "三引号 docstring 写在函数首行，用于说明函数用途。", "source_id": "K013", "fact_id": "F012"}],
      examples: [{"title": "封装求平均分函数", "code": "def average(scores):\n    return sum(scores) / len(scores)\nprint(average([80, 90, 75]))", "explanation": "函数把可复用逻辑封装起来，调用时执行函数体。"}, {"title": "问候函数复用", "code": "def greet(name):\n    print(\"你好，\" + name + \"！\")\n\ngreet(\"小明\")\ngreet(\"小红\")", "explanation": "函数定义后不会立即执行，调用 greet 两次实现代码复用。"}],
      practiceTasks: ["定义求和函数", "调用函数输出结果", "定义一个 greet(name) 函数，调用三次输出不同问候"],
      quizItems: [{"level": 1, "type": "choice", "question": "定义函数使用哪个关键字？", "answer": "def", "sourceId": "K013", "factId": "F001", "options": ["def", "for", "if", "class"]}, {"level": 2, "type": "practice", "question": "请完成一个与“函数定义与调用”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K013", "factId": "F002"}, {"level": 2, "type": "practice", "question": "定义一个函数 is_even(n)，判断 n 是否为偶数。", "answer": "能用 def 定义函数并返回布尔值。", "sourceId": "K013", "factId": "F004"}],
    },
    {
      sourceId: "K014",
      title: "参数与返回值",
      module: "Python基础",
      difficulty: "basic",
      file: "knowledge_base/python_basic/K014_params_return.md",
      snippet: "参数用于把外部数据传入函数。",
      prerequisites: ["K013"],
      keywords: ["参数", "返回值", "return", "函数输入", "函数输出"],
      facts: [{"sourceId": "K014", "factId": "F001", "content": "参数用于把外部数据传入函数。", "source_id": "K014", "fact_id": "F001"}, {"sourceId": "K014", "factId": "F002", "content": "return 用于把函数结果返回给调用者。", "source_id": "K014", "fact_id": "F002"}, {"sourceId": "K014", "factId": "F003", "content": "没有显式 return 的函数默认返回 None。", "source_id": "K014", "fact_id": "F003"}, {"sourceId": "K014", "factId": "F004", "content": "位置参数按调用顺序传入，关键字参数按参数名传入。", "source_id": "K014", "fact_id": "F004"}, {"sourceId": "K014", "factId": "F005", "content": "参数可设默认值，调用时可省略该参数。", "source_id": "K014", "fact_id": "F005"}, {"sourceId": "K014", "factId": "F006", "content": "带默认值的参数必须放在无默认值参数之后。", "source_id": "K014", "fact_id": "F006"}, {"sourceId": "K014", "factId": "F007", "content": "*args 收集任意多个位置参数为元组。", "source_id": "K014", "fact_id": "F007"}, {"sourceId": "K014", "factId": "F008", "content": "**kwargs 收集任意多个关键字参数为字典。", "source_id": "K014", "fact_id": "F008"}, {"sourceId": "K014", "factId": "F009", "content": "return 可返回多个值，调用方收到的是一个元组。", "source_id": "K014", "fact_id": "F009"}, {"sourceId": "K014", "factId": "F010", "content": "函数遇到 return 立即结束，return 后的语句不会执行。", "source_id": "K014", "fact_id": "F010"}, {"sourceId": "K014", "factId": "F011", "content": "实参数量与形参不匹配时会抛出 TypeError。", "source_id": "K014", "fact_id": "F011"}, {"sourceId": "K014", "factId": "F012", "content": "可变对象（如列表）作为默认参数会被共享，应避免使用。", "source_id": "K014", "fact_id": "F012"}],
      examples: [{"title": "带参数和返回值的成绩处理函数", "code": "def calc_average(scores):\n    total = sum(scores)\n    count = len(scores)\n    return total / count\n\ndef get_grade(score):\n    if score >= 90:\n        return \"优秀\"\n    elif score >= 60:\n        return \"及格\"\n    else:\n        return \"不及格\"\n\navg = calc_average([85, 92, 78, 95])\nprint(\"平均分：\", avg)\nprint(\"等级：\", get_grade(avg))", "explanation": "calc_average 接收成绩列表为参数，return 返回平均分；get_grade 根据分数返回等级。"}, {"title": "无 return 的函数", "code": "def show_info(name, score):\n    print(name + \"的成绩是：\" + str(score))\n\nresult = show_info(\"小明\", 92)\nprint(\"返回值：\", result)", "explanation": "没有 return 语句的函数默认返回 None。"}],
      practiceTasks: ["写一个带参数的求和函数并返回值", "写一个函数接收成绩列表返回最高分和最低分", "写函数 add(a, b=10)，分别用 1 个和 2 个参数调用"],
      quizItems: [{"level": 1, "type": "choice", "question": "函数没有写 return 语句时，调用后得到什么？", "answer": "None", "sourceId": "K014", "factId": "F003", "options": ["None", "0", "报错", "最后一个表达式的值"]}, {"level": 2, "type": "practice", "question": "写一个函数 calc(scores)，接收成绩列表，返回最高分、最低分和平均分三个值。", "answer": "能使用 return 返回多个值（元组）。", "sourceId": "K014", "factId": "F002"}, {"level": 2, "type": "practice", "question": "写函数 add_all(*nums)，返回所有参数之和。", "answer": "能使用 *args 收集任意数量参数。", "sourceId": "K014", "factId": "F007"}],
    },
    {
      sourceId: "K015",
      title: "文件读写",
      module: "Python基础",
      difficulty: "intermediate",
      file: "knowledge_base/python_basic/K015_file_io.md",
      snippet: "open 可用于打开文件。",
      prerequisites: ["K003", "K012"],
      keywords: ["文件", "读取", "写入", "open", "read", "write", "文本文件"],
      facts: [{"sourceId": "K015", "factId": "F001", "content": "open 可用于打开文件。", "source_id": "K015", "fact_id": "F001"}, {"sourceId": "K015", "factId": "F002", "content": "read 可读取文件内容。", "source_id": "K015", "fact_id": "F002"}, {"sourceId": "K015", "factId": "F003", "content": "写文件时应明确写入模式并注意覆盖风险。", "source_id": "K015", "fact_id": "F003"}, {"sourceId": "K015", "factId": "F004", "content": "open 的第二个参数是打开模式，如 \"r\"、\"w\"、\"a\"。", "source_id": "K015", "fact_id": "F004"}, {"sourceId": "K015", "factId": "F005", "content": "with 语句能自动关闭文件，避免资源泄漏。", "source_id": "K015", "fact_id": "F005"}, {"sourceId": "K015", "factId": "F006", "content": "readline() 逐行读取，readlines() 返回所有行组成的列表。", "source_id": "K015", "fact_id": "F006"}, {"sourceId": "K015", "factId": "F007", "content": "直接迭代文件对象可逐行处理大文件，节省内存。", "source_id": "K015", "fact_id": "F007"}, {"sourceId": "K015", "factId": "F008", "content": "\"a\" 追加模式在文件末尾写入，不覆盖原有内容。", "source_id": "K015", "fact_id": "F008"}, {"sourceId": "K015", "factId": "F009", "content": "文件写入后需关闭（或用 with），否则内容可能没有落盘。", "source_id": "K015", "fact_id": "F009"}, {"sourceId": "K015", "factId": "F010", "content": "指定 encoding=\"utf-8\" 可正确读写中文文本文件。", "source_id": "K015", "fact_id": "F010"}, {"sourceId": "K015", "factId": "F011", "content": "以 \"r\" 打开不存在的文件会抛出 FileNotFoundError。", "source_id": "K015", "fact_id": "F011"}, {"sourceId": "K015", "factId": "F012", "content": "\"rb\"、\"wb\" 等二进制模式用于读写非文本文件。", "source_id": "K015", "fact_id": "F012"}],
      examples: [{"title": "读取成绩文件", "code": "with open(\"scores.txt\", \"r\", encoding=\"utf-8\") as f:\n    content = f.read()\n    print(\"文件内容：\")\n    print(content)", "explanation": "with 语句自动管理文件关闭，read() 一次性读取全部内容。"}, {"title": "写入统计结果", "code": "students = [\"小明:92\", \"小红:85\", \"小刚:78\"]\nwith open(\"report.txt\", \"w\", encoding=\"utf-8\") as f:\n    for student in students:\n        f.write(student + \"\\n\")\nprint(\"报告已写入 report.txt\")", "explanation": "\"w\" 写入模式会覆盖已有文件；每次 write 写入一行，需手动加换行符。"}],
      practiceTasks: ["读取文本文件内容并统计行数", "把学生成绩逐行写入文件", "用 with 读取文本文件并逐行输出内容"],
      quizItems: [{"level": 1, "type": "choice", "question": "使用 open 的 \"w\" 模式打开一个已有文件会？", "answer": "覆盖原文件", "sourceId": "K015", "factId": "F003", "options": ["追加内容", "覆盖原文件", "报错", "只读打开"]}, {"level": 2, "type": "practice", "question": "写代码：把程序中的学生姓名和成绩逐行写入 score_report.txt，每行格式为\"姓名：成绩\"。", "answer": "能用 with + write 完成文件写入。", "sourceId": "K015", "factId": "F001"}, {"level": 1, "type": "choice", "question": "以下哪个模式会在文件末尾追加内容而不覆盖？", "answer": "\"a\"", "sourceId": "K015", "factId": "F008", "options": ["\"r\"", "\"w\"", "\"a\"", "\"rb\""]}],
    },
    {
      sourceId: "K016",
      title: "异常处理",
      module: "Python基础",
      difficulty: "intermediate",
      file: "knowledge_base/python_basic/K016_exception.md",
      snippet: "try/except 用于捕获并处理运行时异常。",
      prerequisites: ["K006"],
      keywords: ["异常", "报错", "try", "except", "错误处理"],
      facts: [{"sourceId": "K016", "factId": "F001", "content": "try/except 用于捕获并处理运行时异常。", "source_id": "K016", "fact_id": "F001"}, {"sourceId": "K016", "factId": "F002", "content": "异常处理可以避免程序因可预期错误直接终止。", "source_id": "K016", "fact_id": "F002"}, {"sourceId": "K016", "factId": "F003", "content": "except 分支应针对具体错误给出处理逻辑。", "source_id": "K016", "fact_id": "F003"}, {"sourceId": "K016", "factId": "F004", "content": "未捕获的异常会导致程序终止，并打印错误回溯信息。", "source_id": "K016", "fact_id": "F004"}, {"sourceId": "K016", "factId": "F005", "content": "except 后可指定异常类型，如 ValueError、ZeroDivisionError。", "source_id": "K016", "fact_id": "F005"}, {"sourceId": "K016", "factId": "F006", "content": "else 子句在 try 块未发生异常时执行。", "source_id": "K016", "fact_id": "F006"}, {"sourceId": "K016", "factId": "F007", "content": "finally 子句无论是否异常都会执行，适合释放资源。", "source_id": "K016", "fact_id": "F007"}, {"sourceId": "K016", "factId": "F008", "content": "raise 语句可主动抛出指定异常。", "source_id": "K016", "fact_id": "F008"}, {"sourceId": "K016", "factId": "F009", "content": "一个 try 可搭配多个 except 分支处理不同异常。", "source_id": "K016", "fact_id": "F009"}, {"sourceId": "K016", "factId": "F010", "content": "except Exception 可捕获大多数异常，但应避免过度使用。", "source_id": "K016", "fact_id": "F010"}, {"sourceId": "K016", "factId": "F011", "content": "用 except ... as e 可获取异常对象并读取错误信息。", "source_id": "K016", "fact_id": "F011"}, {"sourceId": "K016", "factId": "F012", "content": "异常类型存在继承关系，如 FileNotFoundError 是 OSError 的子类。", "source_id": "K016", "fact_id": "F012"}],
      examples: [{"title": "处理数字转换异常", "code": "user_input = input(\"请输入成绩：\")\ntry:\n    score = int(user_input)\n    if score >= 60:\n        print(\"及格\")\n    else:\n        print(\"不及格\")\nexcept ValueError:\n    print(\"输入无效，请输入数字。\")", "explanation": "当用户输入非数字字符串时，int() 抛出 ValueError，被 except 捕获后给出友好提示。"}, {"title": "处理文件操作异常", "code": "filename = input(\"请输入文件名：\")\ntry:\n    with open(filename, \"r\", encoding=\"utf-8\") as f:\n        print(f.read())\nexcept FileNotFoundError:\n    print(\"文件不存在，请检查文件名。\")\nexcept PermissionError:\n    print(\"没有权限读取该文件。\")", "explanation": "针对不同类型的异常分别处理，比捕获所有异常更精确。"}],
      practiceTasks: ["用 try/except 处理数字转换和除零错误", "写一个 safe_divide(a, b) 函数处理除零异常", "写代码捕获 int() 转换非数字输入时抛出的 ValueError"],
      quizItems: [{"level": 1, "type": "choice", "question": "如果 try 块中没有抛出异常，except 块会执行吗？", "answer": "不会", "sourceId": "K016", "factId": "F001", "options": ["会", "不会", "看情况", "报错"]}, {"level": 2, "type": "practice", "question": "写一个 safe_divide(a, b) 函数，返回 a/b 的结果，如果 b 为 0 则返回\"除数不能为0\"。", "answer": "能用 try/except 捕获 ZeroDivisionError。", "sourceId": "K016", "factId": "F002"}, {"level": 2, "type": "practice", "question": "用 try/except/finally 写代码：读取文件，无论是否成功最后都打印\"结束\"。", "answer": "能正确使用 finally 子句。", "sourceId": "K016", "factId": "F007"}],
    },
    {
      sourceId: "K017",
      title: "模块导入",
      module: "Python基础",
      difficulty: "intermediate",
      file: "knowledge_base/python_basic/K017_import.md",
      snippet: "import 用于导入模块。",
      prerequisites: ["K013"],
      keywords: ["import", "模块", "导入", "库", "复用代码"],
      facts: [{"sourceId": "K017", "factId": "F001", "content": "import 用于导入模块。", "source_id": "K017", "fact_id": "F001"}, {"sourceId": "K017", "factId": "F002", "content": "模块可以复用其他文件或标准库中的功能。", "source_id": "K017", "fact_id": "F002"}, {"sourceId": "K017", "factId": "F003", "content": "from ... import ... 可导入模块中的指定对象。", "source_id": "K017", "fact_id": "F003"}, {"sourceId": "K017", "factId": "F004", "content": "import math 后需用 math.sqrt 形式调用模块中的对象。", "source_id": "K017", "fact_id": "F004"}, {"sourceId": "K017", "factId": "F005", "content": "可用 as 为模块起别名，如 import numpy as np。", "source_id": "K017", "fact_id": "F005"}, {"sourceId": "K017", "factId": "F006", "content": "from math import * 导入所有公开名称，一般应避免使用。", "source_id": "K017", "fact_id": "F006"}, {"sourceId": "K017", "factId": "F007", "content": "math、random、os 等标准库随 Python 一起安装。", "source_id": "K017", "fact_id": "F007"}, {"sourceId": "K017", "factId": "F008", "content": "import 语句通常放在脚本文件的开头。", "source_id": "K017", "fact_id": "F008"}, {"sourceId": "K017", "factId": "F009", "content": "同一个模块被多次导入时只执行一次初始化。", "source_id": "K017", "fact_id": "F009"}, {"sourceId": "K017", "factId": "F010", "content": "自己编写的 .py 文件也可以作为模块被导入。", "source_id": "K017", "fact_id": "F010"}, {"sourceId": "K017", "factId": "F011", "content": "sys.path 列表决定导入时模块的搜索路径。", "source_id": "K017", "fact_id": "F011"}, {"sourceId": "K017", "factId": "F012", "content": "用 if __name__ == \"__main__\" 判断模块是否作为主程序运行。", "source_id": "K017", "fact_id": "F012"}],
      examples: [{"title": "用 math 模块计算统计值", "code": "import math\n\nscores = [85, 92, 78, 95, 88]\nmean = sum(scores) / len(scores)\nstd_dev = math.sqrt(sum((x - mean) ** 2 for x in scores) / len(scores))\nprint(\"平均分：\", round(mean, 2))\nprint(\"标准差：\", round(std_dev, 2))", "explanation": "import math 导入整个 math 模块，math.sqrt 使用其中的平方根函数。"}, {"title": "从模块导入指定函数", "code": "from math import sqrt, pi\n\nr = 5\narea = pi * r ** 2\nprint(\"半径为\", r, \"的圆面积：\", round(area, 2))\n\nresult = sqrt(144)\nprint(\"144 的平方根：\", result)", "explanation": "from ... import ... 只导入需要的函数或常量，调用时无需加模块前缀。"}],
      practiceTasks: ["导入 random 模块生成随机数", "使用 math 模块计算圆周长和面积", "导入 random 模块，生成一个 1 到 10 的随机整数"],
      quizItems: [{"level": 1, "type": "choice", "question": "以下哪种方式导入后可以直接调用 sqrt(9) 而不需要写 math.sqrt(9)？", "answer": "from math import sqrt", "sourceId": "K017", "factId": "F003", "options": ["import math", "from math import sqrt", "include math", "import *"]}, {"level": 2, "type": "practice", "question": "导入 random 模块，写代码生成 5 个 1 到 100 之间的随机整数并输出。", "answer": "能正确使用 random.randint()。", "sourceId": "K017", "factId": "F002"}, {"level": 1, "type": "choice", "question": "为模块起别名使用哪个关键字？", "answer": "as", "sourceId": "K017", "factId": "F005", "options": ["as", "alias", "name", "use"]}],
    },
    {
      sourceId: "K018",
      title: "成绩统计器综合项目",
      module: "Python基础",
      difficulty: "integrated",
      file: "knowledge_base/python_basic/K018_score_project.md",
      snippet: "成绩统计项目可综合练习列表、循环和函数。",
      prerequisites: ["K007", "K009", "K013"],
      keywords: ["成绩统计", "综合项目", "循环", "列表", "函数", "平均分"],
      facts: [{"sourceId": "K018", "factId": "F001", "content": "成绩统计项目可综合练习列表、循环和函数。", "source_id": "K018", "fact_id": "F001"}, {"sourceId": "K018", "factId": "F002", "content": "成绩列表可以用 for 循环逐项累计求和。", "source_id": "K018", "fact_id": "F002"}, {"sourceId": "K018", "factId": "F003", "content": "把统计逻辑封装为函数可提升复用性。", "source_id": "K018", "fact_id": "F003"}, {"sourceId": "K018", "factId": "F004", "content": "最高分和最低分可直接用内置函数 max() 与 min() 获取。", "source_id": "K018", "fact_id": "F004"}, {"sourceId": "K018", "factId": "F005", "content": "平均分用 sum(scores) / len(scores) 计算，注意 len 为 0 会除零。", "source_id": "K018", "fact_id": "F005"}, {"sourceId": "K018", "factId": "F006", "content": "空成绩列表直接求平均会抛出 ZeroDivisionError，应提前判断。", "source_id": "K018", "fact_id": "F006"}, {"sourceId": "K018", "factId": "F007", "content": "可用 input 循环录入成绩，并存入列表。", "source_id": "K018", "fact_id": "F007"}, {"sourceId": "K018", "factId": "F008", "content": "统计结果可用 f-string 格式化输出，如保留两位小数。", "source_id": "K018", "fact_id": "F008"}, {"sourceId": "K018", "factId": "F009", "content": "项目可拆分为录入、统计、输出等函数，各司其职。", "source_id": "K018", "fact_id": "F009"}, {"sourceId": "K018", "factId": "F010", "content": "sorted() 可对成绩排序，便于输出排名。", "source_id": "K018", "fact_id": "F010"}, {"sourceId": "K018", "factId": "F011", "content": "统计及格人数可用循环加条件判断逐个累计。", "source_id": "K018", "fact_id": "F011"}, {"sourceId": "K018", "factId": "F012", "content": "项目完成后可用文件读写保存结果，便于长期留存。", "source_id": "K018", "fact_id": "F012"}],
      examples: [{"title": "成绩统计器最小项目", "code": "def average(scores):\n    return sum(scores) / len(scores)\n\nscores = [80, 90, 75]\nprint(max(scores), min(scores), average(scores))", "explanation": "成绩统计项目把列表、循环/聚合和函数组合成完整任务。"}, {"title": "录入成绩并统计及格人数", "code": "scores = []\nfor _ in range(3):\n    scores.append(int(input(\"请输入成绩：\")))\npassed = 0\nfor s in scores:\n    if s >= 60:\n        passed += 1\nprint(f\"及格人数：{passed}，平均分：{sum(scores) / len(scores):.1f}\")", "explanation": "项目综合 input 录入、for 循环、列表、条件判断与 f-string 格式化输出。"}],
      practiceTasks: ["实现成绩平均分函数", "输出最高分、最低分和平均分", "给成绩统计器增加录入功能：用 input 输入 3 个成绩再统计"],
      quizItems: [{"level": 1, "type": "short", "question": "成绩统计器综合项目通常至少组合哪些知识？", "answer": "列表、循环和函数", "sourceId": "K018", "factId": "F001"}, {"level": 2, "type": "practice", "question": "请完成一个与“成绩统计器综合项目”相关的小练习。", "answer": "能正确运用该知识点并解释关键步骤。", "sourceId": "K018", "factId": "F002"}, {"level": 2, "type": "practice", "question": "给成绩统计器增加功能：输出成绩排名（从高到低）。", "answer": "能用 sorted() 对列表排序。", "sourceId": "K018", "factId": "F010"}],
    },
  ],
})
